config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'items#index'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resources :cards, only: [:new, :create, :destroy]
  end
  resources :items do
    resources :orders, only: [:index, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :categories do
    collection do
      get 'id2', 'id3', 'id4', 'id5', 'id6', 'id7', 'id8', 'id9', 'id10'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :items, dependent: :destroy
  has_many :orders
  has_many :comments, dependent: :destroy
  has_many :commented_items, through: :comments, source: :item
  has_many :sns_credentials, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item

  with_options presence: true do
    validates :name
    validates :nickname, uniqueness: { case_sensitive: true }
  end

  def already_liked?(item)
    likes.exists?(item_id: item.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  private

  def authorization
    sns_info = User.from_omniauth(request.env['omniauth.auth'])
    @user = sns_info[:user]

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :block_mypage, only: :show
  before_action :block_edit, only: :edit

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def show
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    card = Card.find_by(user_id: current_user.id)

    if @user.card
      customer = Payjp::Customer.retrieve(card.customer_token)
      @card = customer.cards.first
    end

    @items = Item.where(user_id: current_user.id).order('created_at DESC')
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :nickname, :email)
  end

  def block_mypage
    user = User.find(params[:id])
    return redirect_to new_user_registration_path unless current_user

    redirect_to root_path if current_user != user
  end

  def block_edit
    user = User.find(params[:id])
    redirect_to root_path if !current_user || current_user != user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @user, url: "/users/#{@user.id}", class: 'registration-main', local: true do |f| %>

  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        アカウント編集
      </h1>
    </div>

    <%# エラーメッセージ %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# // エラーメッセージ %>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">氏名</label>
      </div>
      <%= f.text_area :name, class:"input-default", id:"name", placeholder:"例) 北海　太郎", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ユーザー名</label>
      </div>
      <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) dosanco_hans", maxlength:"40" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">メールアドレス</label>
      </div>
      <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
    </div>
 
    <div class="form-group">
      <p class='form-info-header'>
        本人確認
      </p>
      <p class='form-info-text'>
        安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
      </p>
    </div>
  
    <div class='register-btn'>
      <%= f.submit "編集する" ,class:"register-red-btn" %>
    </div>
    <div class="user-delete-btn">
      <%= link_to 'アカウントを削除', "/users/#{@user.id}", method: :delete, class: "user-delete-text" %>
    </div>
  </div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='mypage-title'>
  <h2 class='title'>User's page << <%= @user.nickname%></h2>
</div>

 <%# 「いいね」した商品の一覧 %>
<div class='item-contents'>
  <h2 class='title'>「いいね」した商品</h2>
  <ul class='item-lists'>

    <%# 商品があればすべて展開 %>
    <% @user.liked_items.order('created_at DESC').first(20).each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>

            <%# 商品が売れていればsold out表示%>
            <% if item.order %>
              <div class='sold-out'>
                <span>Sold Out</span>
              </div>
            <% end %>
            <%# // 商品が売れていればsold out表示%>

          </div>
          <div class='item-info'>
            <div class='item-name'>
              <%= item.name if item.name.length <= 20  %>
              <%= item.name.slice(0..19) + "…" if item.name.length >= 21 %>
            </div>
            <div class='item-bottom-info'>
              <div class='item-price'>
                <span><%= item.price.to_s(:delimited) %>円</span>
              </div>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= Like.where(item_id: item.id).count %></span>
                <%= image_tag "comment2.png", class:"comment-icon" %>
                <span class='comment-count'><%= Comment.where(item_id: item.id).count %></span>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品があればすべて展開 %>

    <%# 商品がない場合のダミー %>
    <% unless @user.liked_items.exists?%>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
          <div class='search-item-nil'>
            <h3 class='item-name'>
              <p>まだ「いいね」した商品がありません</p>
            </h3>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品がない場合のダミー %>
      
  </ul>
</div>
<%# //「いいね」した商品の一覧 %>

<%# 出品した商品の一覧 %>
<div class='item-contents'>
  <h2 class='title'>出品した商品</h2>
  <ul class='item-lists'>

    <%# 商品があればすべて展開 %>
    <% @items.first(20).each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>

            <%# 商品が売れていればsold out表示%>
            <% if item.order %>
              <div class='sold-out'>
                <span>Sold Out</span>
              </div>
            <% end %>
            <%# // 商品が売れていればsold out表示%>

          </div>
          <div class='item-info'>
            <div class='item-name'>
              <%= item.name if item.name.length <= 20  %>
              <%= item.name.slice(0..19) + "…" if item.name.length >= 21 %>
            </div>
            <div class='item-bottom-info'>
              <div class='item-price'>
                <span><%= item.price.to_s(:delimited) %>円</span>
              </div>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= Like.where(item_id: item.id).count %></span>
                <%= image_tag "comment2.png", class:"comment-icon" %>
                <span class='comment-count'><%= Comment.where(item_id: item.id).count %></span>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品があればすべて展開 %>

    <%# 商品がない場合のダミー %>
    <% unless @items.exists?%>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
          <div class='search-item-nil'>
            <h3 class='item-name'>
              <p>まだ出品した商品がありません</p>
            </h3>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品がない場合のダミー %>
      
  </ul>
</div>

<%# //出品した商品の一覧 %>

<%# マイページ情報 %>
<div class="item-show">
  <div class="item-box">  

    <%# アカウント情報 %>
    <div class="account-title">
      <span><%= "アカウント情報" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">氏名</th>
          <td class="detail-value"><%= @user.name %></td>
        </tr>
        <tr>
          <th class="detail-item">ユーザー名</th>
          <td class="detail-value"><%= @user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">Email</th>
          <td class="detail-value"><%= @user.email %></td>
        </tr>
        <tr>
          <th class="detail-item">パスワード</th>
          <td class="detail-value"><%= "********" %></td>
        </tr>
      </tbody>
    </table>
 
    <%= link_to 'アカウントの編集', edit_user_path(current_user), class: "item-red-btn" %>
    <%# // アカウント情報 %>

    <%# カード情報 %>
    <%# カード登録の有無で処理区別 %>
    <% if @user.card %>
      <div class="card-title">
        <span><%= "カード情報" %></span>
      </div>
      <table class="detail-table">
        <tbody>
          <tr>
            <th class="detail-item">カード番号</th>
            <td class="detail-value"><%= "**** **** **** " + @card[:last4] %></td>
          </tr>
          <tr>
            <th class="detail-item">有効期限</th>
            <td class="detail-value"><%= "#{@card[:exp_month]} / #{@card[:exp_year]}" %></td>
          </tr>
        </tbody>
      </table>
      <%= link_to 'カードの登録を解除', user_card_path(@user.card.id), method: :delete, class:"item-red-btn" %>  
    <% else %>
      <%= link_to 'カード情報の登録', new_user_card_path(current_user) ,class:"item-red-btn"%>
    <% end %>
    <%# // カード登録の有無で処理区別 %>
    <%# //カード情報 %>
    
  </div>
</div>

<%= render "shared/footer" %>