config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'items#index'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resources :cards, only: [:new, :create, :destroy]
  end
  resources :items do
    resources :orders, only: [:index, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :categories do
    collection do
      get 'id2', 'id3', 'id4', 'id5', 'id6', 'id7', 'id8', 'id9', 'id10'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :card_token, :customer_token, presence: true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '家具・雑貨' },
    { id: 3, name: 'アクセサリー' },
    { id: 4, name: '服・ファッション' },
    { id: 5, name: 'デザインマスク' },
    { id: 6, name: 'バッグ・財布・ポシェット' },
    { id: 7, name: 'ニット・編み物' },
    { id: 8, name: 'ぬいぐるみ・おもちゃ' },
    { id: 9, name: 'アート' },
    { id: 10, name: 'その他' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '在庫あり/即日出荷' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '1週間以内に発送' },
    { id: 5, name: '2週間以内に発送' },
    { id: 6, name: '1ヵ月以内に発送' },
    { id: 7, name: '1ヵ月以上かかります' }
  ]
end

app/models/from.rb
class From < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '札幌' },
    { id: 3, name: '旭川' },
    { id: 4, name: '函館' },
    { id: 5, name: '帯広' },
    { id: 6, name: '釧路' },
    { id: 7, name: '北見' },
    { id: 8, name: '稚内' },
    { id: 9, name: '苫小牧' },
    { id: 10, name: '室蘭' },
    { id: 11, name: '小樽' },
    { id: 12, name: '江別' },
    { id: 13, name: '恵庭' },
    { id: 14, name: '北広島' },
    { id: 15, name: 'その他' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one :order
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user
  has_one_attached :image
  belongs_to_active_hash :category
  belongs_to_active_hash :from
  belongs_to_active_hash :day

  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :info, length: { maximum: 1000 }
    validates :image
    validates :price
  end
  validates :price, format: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }
  validates :price, numericality: { greater_than_or_equal_to: 100, less_than_or_equal_to: 9_999_999, message: 'が範囲外です' }
  validates :category_id, :from_id, :day_id, numericality: { other_than: 1, message: 'を選んでください' }

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%").order('created_at DESC')
    else
      Item.includes(:order).order('created_at DESC')
    end
  end

  def previous
    user.items.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.items.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :address, dependent: :destroy
  belongs_to :user
  belongs_to :item
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code, :city, :house_num, :building, :phone, :user_id, :item_id, :token

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'を正しく入力してください' }
    validates :city
    validates :house_num
    validates :phone, format: { with: /\A\d{10}$|^\d{11}\z/, message: 'を正しく入力してください' }
  end

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, city: city, house_num: house_num, building: building, phone: phone, order_id: order.id)
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :items, dependent: :destroy
  has_many :orders
  has_many :comments, dependent: :destroy
  has_many :commented_items, through: :comments, source: :item
  has_many :sns_credentials, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item

  with_options presence: true do
    validates :name
    validates :nickname, uniqueness: { case_sensitive: true }
  end

  def already_liked?(item)
    likes.exists?(item_id: item.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>DosancoHans</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_card_error_messages.html.erb
<% if card.errors.any? %>
<div class="error-alert">
  <ul>
    <% order.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_category_main.html.erb
<div class="category-title">
  <p>New Arrival</p>
</div>

<%# 商品一覧 %>
<div class='second-item-contents'>
  <ul class='item-lists'>

    <%# 商品があればすべて展開 %>
    <% @items.each do |item| %>
      <li class='list'>
        <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img" %>

            <%# 商品が売れていればsold out表示%>
            <% if item.order %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
            <% end %>
            <%# // 商品が売れていればsold out表示%>

          </div>
          <div class='item-info'>
            <div class='item-name'>
              <%= item.name if item.name.length <= 20  %>
              <%= item.name.slice(0..19) + "…" if item.name.length >= 21 %>
            </div>
            <div class='item-bottom-info'>
              <div class='item-price'>
                <span><%= item.price.to_s(:delimited) %>円</span>
              </div>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'><%= Like.where(item_id: item.id).count %></span>
                <%= image_tag "comment2.png", class:"comment-icon" %>
                <span class='comment-count'><%= Comment.where(item_id: item.id).count %></span>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品があればすべて展開 %>

    <%# 商品がない場合のダミー %>
    <% unless @items.exists?%>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
          <div class='search-item-nil'>
            <h3 class='item-name'>
              商品がありません
            </h3>
          </div>
        <% end %>
      </li>
    <% end %>
    <%# // 商品がない場合のダミー %>

  </ul>
</div>
<%# /商品一覧 %>

<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <a href="/items/new"></a>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <div class='download-suggest'>
    <p class='ad-footer-explain'>
      だれでもかんたん、北海道民のためのフリマアプリ
    </p>
    <h2 class='ad-footer-title'>
      今すぐ無料ダウンロード
    </h2>
  </div>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>DosancoHansについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'DosancoHans利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>DosancoHansを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>DosancoHansについて</h2>
      <ul>
        <li><%= link_to 'DosancoHansガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'DosancoHansロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("dosanco_hans_background_black_logo.png", class:"logo-white"), "#" %>
  <p>_____</p>
  <p>　</p>
  <p>© DosancoHans</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("dosanco_hans_logo.png", class:"furima-icon"), "/" %>
    <%= form_with url: search_items_path, method: :get, local: true do |f| %>
      <div class="search-form">
        <%= f.text_area :keyword, placeholder: '商品名を検索する',　class: 'input-box' %>
        <%= f.submit "さがす", class: "search-button" %>
      </div>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li class ="category-list" id="category">▼ カテゴリーから探す</li>
    </ul>
    <ul class='lists-right'>
      <%# ログイン有無の条件分岐 %>
      <% if user_signed_in? %>
        <li><%= link_to "#{current_user.nickname}さんのマイページ", user_path(current_user.id), class: "user-nickname" %></li> 
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
      <%# // ログイン有無の条件分岐 %>
    </ul>
  </div>

  <%# カテゴリーリスト%>
   <ul class="category-show-lists hidden" id="pull-down">
      <li class="pull-down-list">
        <%= link_to '家具・雑貨', id2_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'アクセサリー', id3_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to '服・ファッション', id4_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'デザインマスク', id5_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'バッグ・財布・ポシェット', id6_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'ニット・編み物', id7_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'ぬいぐるみ・おもちゃ', id8_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'アート', id9_categories_path, class: "category-name" %>
      </li>
      <li class="pull-down-list">
        <%= link_to 'その他', id10_categories_path, class: "category-name" %>
      </li>
    </ul>
    <%# // カテゴリーリスト%>
</header>

app/views/shared/_order_error_messages.html.erb
<% if order.errors.any? %>
<div class="error-alert">
  <ul>
    <% order.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <div class='second-header'>
    <%= link_to image_tag("dosanco_hans_background_grey_logo.png", class:"second-logo"), "/" %>
  </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("dosanco_hans_background_grey_logo.png", class:"second-logo"), "/" %>
</header>