config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'items#index'
  resources :users, only: [:edit, :update, :destroy, :show] do
    resources :cards, only: [:new, :create, :destroy]
  end
  resources :items do
    resources :orders, only: [:index, :create]
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :categories do
    collection do
      get 'id2', 'id3', 'id4', 'id5', 'id6', 'id7', 'id8', 'id9', 'id10'
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :card_token, :customer_token, presence: true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '家具・雑貨' },
    { id: 3, name: 'アクセサリー' },
    { id: 4, name: '服・ファッション' },
    { id: 5, name: 'デザインマスク' },
    { id: 6, name: 'バッグ・財布・ポシェット' },
    { id: 7, name: 'ニット・編み物' },
    { id: 8, name: 'ぬいぐるみ・おもちゃ' },
    { id: 9, name: 'アート' },
    { id: 10, name: 'その他' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '在庫あり/即日出荷' },
    { id: 3, name: '2〜3日で発送' },
    { id: 4, name: '1週間以内に発送' },
    { id: 5, name: '2週間以内に発送' },
    { id: 6, name: '1ヵ月以内に発送' },
    { id: 7, name: '1ヵ月以上かかります' }
  ]
end

app/models/from.rb
class From < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '札幌' },
    { id: 3, name: '旭川' },
    { id: 4, name: '函館' },
    { id: 5, name: '帯広' },
    { id: 6, name: '釧路' },
    { id: 7, name: '北見' },
    { id: 8, name: '稚内' },
    { id: 9, name: '苫小牧' },
    { id: 10, name: '室蘭' },
    { id: 11, name: '小樽' },
    { id: 12, name: '江別' },
    { id: 13, name: '恵庭' },
    { id: 14, name: '北広島' },
    { id: 15, name: 'その他' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_one :order
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user
  has_one_attached :image
  belongs_to_active_hash :category
  belongs_to_active_hash :from
  belongs_to_active_hash :day

  with_options presence: true do
    validates :name, length: { maximum: 40 }
    validates :info, length: { maximum: 1000 }
    validates :image
    validates :price
  end
  validates :price, format: { with: /\A[0-9]+\z/, message: 'は半角数字で入力してください' }
  validates :price, numericality: { greater_than_or_equal_to: 100, less_than_or_equal_to: 9_999_999, message: 'が範囲外です' }
  validates :category_id, :from_id, :day_id, numericality: { other_than: 1, message: 'を選んでください' }

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?)', "%#{search}%").order('created_at DESC')
    else
      Item.includes(:order).order('created_at DESC')
    end
  end

  def previous
    user.items.order('created_at desc, id desc').where('created_at <= ? and id < ?', created_at, id).first
  end

  def next
    user.items.order('created_at desc, id desc').where('created_at >= ? and id > ?', created_at, id).reverse.first
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :user_id
end

app/models/order.rb
class Order < ApplicationRecord
  has_one :address, dependent: :destroy
  belongs_to :user
  belongs_to :item
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code, :city, :house_num, :building, :phone, :user_id, :item_id, :token

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'を正しく入力してください' }
    validates :city
    validates :house_num
    validates :phone, format: { with: /\A\d{10}$|^\d{11}\z/, message: 'を正しく入力してください' }
  end

  def save
    order = Order.create(user_id: user_id, item_id: item_id)
    Address.create(postal_code: postal_code, city: city, house_num: house_num, building: building, phone: phone, order_id: order.id)
  end
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :items, dependent: :destroy
  has_many :orders
  has_many :comments, dependent: :destroy
  has_many :commented_items, through: :comments, source: :item
  has_many :sns_credentials, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item

  with_options presence: true do
    validates :name
    validates :nickname, uniqueness: { case_sensitive: true }
  end

  def already_liked?(item)
    likes.exists?(item_id: item.id)
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
      email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :block_new, only: :new
  before_action :block_double, only: :new

  def new
    @card = Card.new
  end

  def create
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    customer = Payjp::Customer.create(
      description: 'test',
      card: params[:card_token]
    )

    card = Card.new(
      card_token: params[:card_token],
      customer_token: customer.id,
      user_id: current_user.id
    )

    if card.save
      move_to_mypage
    else
      move_to_mypage
    end
  end

  def destroy
    card = Card.find(params[:user_id])
    if card.destroy
      move_to_mypage
    else
      move_to_mypage
    end
  end

  private

  def move_to_mypage
    redirect_to user_path(current_user.id)
  end

  def block_new
    user = User.find(params[:user_id])
    redirect_to root_path if !current_user || current_user != user
  end

  def block_double
    move_to_mypage if current_user.card
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show]
  before_action :block_new, only: :new
  before_action :block_edit, only: :edit

  def index
    @items = Item.includes(:order).order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def show
    @comment = Comment.new
    @comments = @item.comments.includes(:user).order('created_at DESC')
    @likes_count = Like.where(item_id: @item.id).count
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :info, :price, :category_id, :from_id, :day_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def block_new
    redirect_to new_user_registration_path unless current_user
  end

  def block_edit
    redirect_to item_path(@item.id) if current_user != @item.user || @item.order
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<%= render "shared/second-header"%>

<%= render 'shared/card_error_messages', card: @card %>

<%= form_with  url: user_cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      クレジットカード登録
    </h1>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">カード番号</label>
    </div>
    <%= f.text_field :number, class:"input-default", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">CVC</label>
    </div>
    <%= f.text_field :cvc, class:"cvc", class:"input-default", placeholder:"カード背面にある3桁の番号", maxlength:"4" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">有効期限</label>
    </div>
    <div class='input-expiration-date-wrap'>
      <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "input-expiration-date"%>
      <p>月</p>
      <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "input-expiration-date"%>
      <p>年</p>
    </div>
  </div>

  <div class='register-btn'>
    <%= f.submit "登録する" , class:"register-red-btn" %>
  </div>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/items/_like.html.erb
<% if !current_user%>
  <% return %>
<% elsif current_user.already_liked?(@item) %>
  <div class="option">
    <div class="favorite-btn" id="favorite">
      <%= link_to item_like_path(@item.id), method: :delete do %>
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <div class="favorite-text">
          <%= "いいね #{@likes_count}" %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="option">
    <div class="favorite-btn" id="favorite">
      <%= link_to item_likes_path(@item.id), method: :post do %>
        <%= image_tag "white_star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span class="favorite-text"><%= "いいね #{@likes_count}" %></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<%# cssは商品出品のものを併用 /items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('dosanco_hans_background_grey_logo.png' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @item, url: "/items/#{@item.id}", local: true do |f| %>

      <%# エラーメッセージ%>
      <%= render 'shared/error_messages', model: f.object %>
      <%# // エラーメッセージ%>

      <%# 出品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          出品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
        <div id="image-list"></div>
      </div>
      <%# /出品画像 %>
      <%# 商品名と商品説明 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :info, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>

      <%# 詳細情報 %>
      <div class="items-detail">
        <div class="weight-bold-text">
          詳細情
        </div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
          <div class="form">
            <div class="weight-bold-text">
              発送元の地域
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:from_id, From.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
            <div class="weight-bold-text">
              発送までの日数
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
          </div>
        </div>
      </div>
      <%# /詳細情報 %>

      <%# 販売価格 %>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥100〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
        </div>
      </div>
      <%# /販売価格 %>

      <%# 注意書き %>
      <div class="caution">
        <p class="sentence">
          <a href="#">禁止されている出品、</a>
          <a href="#">行為</a>
          を必ずご確認ください。
        </p>
        <p class="sentence">
          またブランド品でシリアルナンバー等がある場合はご記載ください。
          <a href="#">偽ブランドの販売</a>
          は犯罪であり処罰される可能性があります。
        </p>
        <p class="sentence">
          また、出品をもちまして
          <a href="#">加盟店規約</a>
          に同意したことになります。
        </p>
      </div>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "変更する" ,class:"sell-btn" %>
      </div>
      <div class="back-btn">
        <%=link_to 'もどる', item_path(@item.id), class:"edit-link-white"%>
      </div>
      <%# /下部ボタン %>
    <% end %>
  </div>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('dosanco_hans_background_grey_logo.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎DosancoHans,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

   <%# 創るたのしさ 使うよろこび ゾーン %>
  <div class='title-contents'>
    <h2 class='service-title'>
      創る楽しさ 使うよろこび
    </h2>
    <p class='service-explain'>
      DasancoHansは道民による道民のための
    </p>
    <p class='service-explain'>
      ハンドメイド作品専門マーケットです
    </p>
  </div>
  <%# /創るたのしさ 使うよろこび ゾーン %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>New Arrival</h2>
    <ul class='item-lists'>
    
      <%# 商品があればすべて展開 %>
      <% @items.first(12).each do |item| %>
        <li class='list'>
          <%= link_to item_path(item.id) do %>
            <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>

              <%# 商品が売れていればsold out表示%>
              <% if item.order %>
                <div class='sold-out'>
                  <span>Sold Out</span>
                </div>
              <% end %>
              <%# //商品が売れていればsold out表示%>

            </div>
            <div class='item-info'>
              <div class='item-name'>
                <%= item.name if item.name.length <= 23  %>
                <%= item.name.slice(0..22) + "…" if item.name.length >= 24 %>
              </div>
              <div class='item-bottom-info'>
                <div class='item-price'>
                  <span><%= item.price.to_s(:delimited) %>円</span>
                </div>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'><%= Like.where(item_id: item.id).count %></span>
                  <%= image_tag "comment2.png", class:"comment-icon" %>
                  <span class='comment-count'><%= Comment.where(item_id: item.id).count %></span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      <%# //商品があればすべて展開 %>

      <%# 商品がない場合のダミー %>
      <% unless @items.exists?%>
        <li class='list'>
          <%= link_to '#' do %>
            <%= image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png", class: "item-img" %>
            <div class='search-item-nil'>
              <h3 class='item-name'>
                商品がありません
              </h3>
            </div>
          <% end %>
        </li>
      <% end %>
      <%# /商品がない場合のダミー %>
    </ul>
  </div>
  <%# /商品一覧 %>

  <%# DosancoHansのメリット ゾーン %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      DosancoHansのメリット
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "furima-intro01.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>3分</span>
          ですぐに出品
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro02.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>シンプル</span>
          な画面
        </h3>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro03.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          手数料
          <span class='reason-list-blue-text'>業界最安</span>
        </h3>
      </li>
    </ul>
  </div>
  <%# /DosancoHansのメリット ゾーン %>
</div>

<div class='purchase-btn'>
  <span class='purchase-btn-text'>出品する</span>
  <%= image_tag 'camera.png' , size: '185x50' ,class: "purchase-btn-icon" %>
  <a href="/items/new"></a>
</div>
<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <%# 商品の概要 %>
  <div class="item-box">
    <h2 class="name">
      <%= @item.name %>
    </h2>
    <div class='item-img-content-show'>
      <%= image_tag @item.image ,class:"item-box-img" %>
      <%# 商品が売れていればsold out表示 %>
      <% if @item.order %>
      <div class='sold-out'>
        <span>Sold Out!!</span>
      </div>
      <% end %>
      <%# //商商品が売れていればsold out表示 %>
    </div>

    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @item.price.to_s(:delimited) %>
      </span>
      <span class="item-postage">
        (税込) 送料込み
      </span>
    </div>

    <%# ログインユーザー = 出品ユーザー の場合の処理 %>
    <% if current_user == @item.user && !@item.order%>
      <%= link_to '商品の編集', edit_item_path(@item.id), class: "item-red-btn" %>
      <%= link_to '出品を削除', "/items/#{@item.id}", method: :delete, class:'item-destroy' %>
    <% end %>
    <%# // ログインユーザー = 出品ユーザー の場合の処理 %>

    <%# 商品が売れていない場合の処理 %>
    <% if user_signed_in? && current_user != @item.user && !@item.order %>
      <%= link_to '購入画面に進む', item_orders_path(@item.id), class: "item-red-btn" %>
      <div class="no-card-mypage">
        ※カード未登録の方は<%= link_to 'マイページ', user_path(current_user.id), class: "edit-link-red"%>に遷移します
      </div>
    <% end %>
    <% unless user_signed_in? %>
      <%= link_to 'まだユーザー登録していない方はこちら', new_user_registration_path %>
    <% end %>
    <%# //商品が売れていない場合の処理  %>
    
    <div class="item-explain-box">
      <div class="item-explain-text">
        【Information】
      </div>
      <%= @item.info %>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">出品者</th>
          <td class="detail-value"><%= @item.user.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @item.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送元の地域</th>
          <td class="detail-value"><%= @item.from.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @item.day.name %></td>
        </tr>
      </tbody>
    </table>

    <%# いいねボタン %>
    <%= render 'like', { item: @item } %>
    <%# /いいねボタン %>
    
  </div>
  <%# /商品の概要 %>

  <%# コメント %>
  <div class="comment-box">

    <%# ログインユーザーと非ログインユーザーの処理区別 %>
    <% if user_signed_in? %>
      <%= form_with model: @comment, url: item_comments_path(@item.id), local: true do |f| %>
        <%= f.text_area :message, class:"comment-text", id:"comment-text", placeholder:"コメント（140文字まで)", maxlength:"140" %>
        <button type="submit" class="comment-btn">
          <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <span>コメントする<span>
        </button>
      <% end %>
    <% else %>
      <div class="non-user-comment">
        <span><%= link_to 'ユーザー登録', new_user_registration_path %>をしてコメントを書こう！</span>
      </div>
    <% end %>
    <%# // ログインユーザーと非ログインユーザーの処理区別 %>

    <div class="comment-second-box">
      <% @comments.each do |comment| %>
        <div class="comment-content">
          <div class="comment-message">
            <span><%= comment.message %></span>
          </div>
          <div class="comment-detail">
            <div class="comment-user-box">
              <div class="comment-user-type">
                <% if @item.user == comment.user %>
                  <span class="seller">出品者</span>
                <% else %>
                  <span class="buyer">投稿者</span>
                <% end %>
              </div>
              <div class="comment-user-name">
                <span><%= comment.user.nickname %></span>
              </div>
            </div>
            <div class="comment-date-title">
              <span>投稿日時</span>
            </div>
            <div class="comment-date">
              <span><%= l comment.created_at %></span>
            </div>
          </div>
          <% if comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to 'コメントを削除', "/items/#{@item.id}/comments/#{comment.id}", method: :delete,  class: "delete-btn" %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%# // コメント %>

  <%# 前後商品リンク %>
  <div class="links">
    <% if @item.previous.present?%>
      <%= link_to item_path(@item.previous), class: "link" do %>
        <p class="change-item-btn">Before</p>
        <%= image_tag @item.previous.image, class: "change-item-img" %>
        <p class="change-item-btn"><%= @item.previous.name if @item.previous.name.length <= 15  %></p>
        <p class="change-item-btn"><%= @item.previous.name.slice(0..14) + "…" if @item.previous.name.length >= 16  %></p>
      <% end %>
    <% end %>
    <% if @item.next.present?%>
      <%= link_to item_path(@item.next), class: "link" do %>
        <p class="change-item-btn">Next</p>
        <%= image_tag @item.next.image ,class:"change-item-img" %>
        <p class="change-item-btn"><%= @item.next.name if @item.next.name.length <= 15  %></p>
        <p class="change-item-btn"><%= @item.next.name.slice(0..14) + "…" if @item.next.name.length >= 16 %></p>
      <% end %>
    <% end %>
  </div>
  <%# // 前後商品リンク %>

  <%# 同一カテゴリーページのサジェスト%>
    <%= link_to ">> #{@item.category.name}をもっと見る", "/categories/id#{@item.category_id}", class: "another-item"%>
  <%# // 同一カテゴリーページのサジェスト%>
  
</div>

<%= render "shared/footer" %>